services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    networks:
      - springboot-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .               # Directory of Dockerfile, typically the project root
      dockerfile: Dockerfile    # Dockerfile name
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/pgdb
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  postgres-data:
